CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    number INTEGER NOT NULL,
    password_hash TEXT NOT NULL,
    role INTEGER NOT NULL
);
